# Generated by Django 4.1.7 on 2023-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_goalcomment_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalcomment',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='goalcomment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
