# Generated by Django 4.1.7 on 2023-03-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tguser_category_tguser_state_tguser_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='title',
        ),
    ]
